-- Create Table Statement

CREATE TABLE employee (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  employment_status BOOLEAN,
  role TEXT,
  reporting_line TEXT
);

INSERT INTO employee (name, employment_status, role, reporting_line)
VALUES 
('John Doe', TRUE, 'Manager', 'Sarah Smith'),
('Jane Smith', TRUE, 'Engineer', 'John Doe'),
('Bob Johnson', FALSE, 'Intern', 'Jane Smith'),
('Sara Lee', TRUE, 'Senior Engineer', 'John Doe'),
('Alex Nguyen', TRUE, 'Data Analyst', 'John Doe'),
('Ashley Kim', TRUE, 'HR Specialist', 'John Doe');



-- Delete Table Statement

DROP TABLE employee;




      